### PR TITLE
 Added AGGeometricKitiOS.framework target and Playground

### PR DESCRIPTION
**Pull request by jamztang**
Great library first of all, I was working on a side project and looking for perspective transformation, during experimentation I made a few changes to play with this library easier.

1. A framework target for more convenient project integration.
2. A playground is to demonstrate the successful of framework creation, and also double as a visual documentation.

aggeometrykit-playground

I think that would also be useful for others.

I am still experimenting this with OS X, I suspect issues with flipped view coordinates, but again, well done on wrapping this into a library, I think we've a great start on cross platform support.

Hope you like the changes.

### CODE REVIEW

**Comment by hfossli** [comment]
Ooooo!! Nice. I like this! I'm offsite now, but will have a look at this tomorrow.

**Comment by jamztang** [comment]
Sure, let me know what I can help

**Comment by hfossli** [comment]
I'm not able to run the playgrounds and I'm not sure what the issue is..

```
Playground execution failed: error: Couldn't lookup symbols:
  _AGKQuadMake
  _CATransform3DWithAGKQuadFromRect
```

Seems related to the framework target `AGGeometryKitiOS`

**Comment by hfossli** [comment]
screen shot 2015-07-21 at 13 59 32

**Comment by jamztang** [comment]
You may have to manually switch to the framework target and compile, not sure if there's a way to automate it.




I am using Xcode 7 beta FYR



—

**Comment by hfossli** [comment]
Okay, I'm on 6.4. I'll try the beta.

**Comment by hfossli** [comment]
Got it working now. Will push to master soon. 

I have restructured the demo project. There is no "source" folder in the demo project anymore. Everything is being linked with cocoapods. Even the playground.

**Comment by hfossli** [comment]
I'm closing the pull request as the contents of the playground is now accessible on master. Feel free to reopen or open a new issue for further discussion about the playground. :)

**Pull request closed without merging**
